In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

movies_df = pd.read_csv("Datasets/clean_movies.csv")
cast_df = pd.read_csv("Datasets/clean_cast.csv")

movies_df['profit'] = movies_df['revenue'] - movies_df['budget']
movies_df['not_flop'] = (movies_df['profit'] > 0)

In [49]:
cast_overlap = pd.merge(movies_df, cast_df, left_on='id', right_on='movie_id')

In [50]:
cast_overlap

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,video,vote_average,vote_count,keywords,movie_text,profit,not_flop,movie_id,actor_name,character
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,False,7.7,5415.0,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",animation comedy family jealousy toy boy frien...,343554033.0,True,862.0,Tom Hanks,Woody (voice)
1,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,False,7.7,5415.0,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",animation comedy family jealousy toy boy frien...,343554033.0,True,862.0,Tim Allen,Buzz Lightyear (voice)
2,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,False,7.7,5415.0,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",animation comedy family jealousy toy boy frien...,343554033.0,True,862.0,Don Rickles,Mr. Potato Head (voice)
3,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,False,7.7,5415.0,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",animation comedy family jealousy toy boy frien...,343554033.0,True,862.0,Jim Varney,Slinky Dog (voice)
4,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,False,7.7,5415.0,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",animation comedy family jealousy toy boy frien...,343554033.0,True,862.0,Wallace Shawn,Rex (voice)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570740,False,NaN,24000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,47871,tt0082525,en,Honky Tonk Freeway,"Ticlaw, a small town in Florida, has only one ...",...,False,0.0,0.0,[],action comedy promises are made in heaven - bu...,-23060577.0,False,47871.0,Celia Weston,Grace
570741,False,NaN,24000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,47871,tt0082525,en,Honky Tonk Freeway,"Ticlaw, a small town in Florida, has only one ...",...,False,0.0,0.0,[],action comedy promises are made in heaven - bu...,-23060577.0,False,47871.0,Deborah Rush,Sister Mary Magdalene
570742,False,NaN,24000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,47871,tt0082525,en,Honky Tonk Freeway,"Ticlaw, a small town in Florida, has only one ...",...,False,0.0,0.0,[],action comedy promises are made in heaven - bu...,-23060577.0,False,47871.0,Geraldine Page,Sister Mary Clarise
570743,False,NaN,24000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,47871,tt0082525,en,Honky Tonk Freeway,"Ticlaw, a small town in Florida, has only one ...",...,False,0.0,0.0,[],action comedy promises are made in heaven - bu...,-23060577.0,False,47871.0,George Dzundza,Eugene
570744,False,NaN,24000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,47871,tt0082525,en,Honky Tonk Freeway,"Ticlaw, a small town in Florida, has only one ...",...,False,0.0,0.0,[],action comedy promises are made in heaven - bu...,-23060577.0,False,47871.0,Joe Grifasi,Osvaldo

In [51]:
jackson_movies = cast_overlap[cast_overlap['actor_name'].str.contains("Samuel L. Jackson")]
paul_movies = cast_overlap[cast_overlap['actor_name'].str.contains("Paul Giamatti")]

In [52]:
jackson_movies[['original_title', 'actor_name', 'profit', 'not_flop']].sort_values('profit',ascending=False)

,original_title,actor_name,profit,not_flop
268865,The Avengers,Samuel L. Jackson,1.299558e+09,True
373536,Avengers: Age of Ultron,Samuel L. Jackson,1.125404e+09,True
8022,Jurassic Park,Samuel L. Jackson,8.571000e+08,True
43277,Star Wars: Episode I - The Phantom Menace,Samuel L. Jackson,8.093176e+08,True
161266,Star Wars: Episode III - Revenge of the Sith,Samuel L. Jackson,7.370000e+08,True
...,...,...,...,...
117960,Twisted,Samuel L. Jackson,-2.480500e+07,False
196686,Cleaner,Samuel L. Jackson,-2.500000e+07,False
321934,Oldboy,Samuel L. Jackson,-2.513898e+07,False
4237,Kiss of Death,Samuel L. Jackson,-4.000000e+07,False
29210,Sphere,Samuel L. Jackson,-6.190000e+07,False

In [40]:
paul_movies[['original_title', 'actor_name', 'profit']].sort_values('profit',ascending=False)

                  original_title     actor_name       profit
332353  The Amazing Spider-Man 2  Paul Giamatti  505717432.0
33653        Saving Private Ryan  Paul Giamatti  411840909.0
406021               San Andreas  Paul Giamatti  360490832.0
77029         Planet of the Apes  Paul Giamatti  262211740.0
25963   My Best Friend's Wedding  Paul Giamatti  261288605.0
...                          ...            ...          ...
268597                  Ironclad  Paul Giamatti  -25000000.0
175823         Lady in the Water  Paul Giamatti  -32714831.0
53138            Man on the Moon  Paul Giamatti  -34565570.0
1909            Before and After  Paul Giamatti  -35000000.0
144                      Sabrina  Paul Giamatti  -58000000.0

[78 rows x 3 columns]

In [37]:
print("$" , jackson_movies['profit'].sum())
print("$" , paul_movies['profit'].sum())

$ 12253955644.0
$ 3442511363.0

In [55]:
print(jackson_movies['not_flop'].value_counts())
print(paul_movies['not_flop'].value_counts())

not_flop
True     62
False    62
Name: count, dtype: int64
not_flop
False    41
True     37
Name: count, dtype: int64